version: "3"
services:
    
  pupper-robot:
    image: ros-humble-greengrass-minipupper:latest
    command: ros2 launch mini_pupper_dance ndance.launch.py  hardware_connected:=false
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - GAZEBO_MASTER_URI=http://localhost:5555
      - ROS_MASTER_URI=http://localhost:11311
      - DANCE_CONFIG=/home/robomaker/routines
      - HARDWARE=true
    network_mode: "host"
    privileged: true
    user: root
    volumes:
      - /greengrass:/greengrass
      - /dev:/dev
      - /sys:/sys
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /tmp/esp32-proxy.socket:/tmp/esp32-proxy.socket
      - /home/ggc_user/routines:/home/robomaker/routines
      - /home/ggc_user/aws_iot_params.yaml:/config/aws_iot_params.yaml
      
  greengrass_bridge:
    image: ros-humble-greengrass-minipupper:latest
    command: ros2 launch greengrass_bridge greengrass_bridge.launch.py ros_topics:="['dance_config']" iot_topics:="['cloud_dance_config']"
    environment:
      - AWS_REGION
      - SVCUID
      - AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT
      - AWS_CONTAINER_AUTHORIZATION_TOKEN
      - AWS_CONTAINER_CREDENTIALS_FULL_URI
    volumes: 
      - "/greengrass/v2/ipc.socket:/greengrass/v2/ipc.socket"
