---
RecipeFormatVersion: '2020-01-25'
ComponentName: com.example.ros.pupper.dance
ComponentVersion: '1.0.0'
ComponentDescription: 'The ROS Pupper Dance Application'
ComponentPublisher: Amazon
ComponentDependencies:
  aws.greengrass.DockerApplicationManager:
    VersionRequirement: ~2.0.0
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ~2.0.0
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        com.example.PubSubPublisher:pubsub:1:
          policyDescription: "Allows access to publish and subscribe to MQTT topics."
          operations:
          - "aws.greengrass#PublishToIoTCore"
          - "aws.greengrass#SubscribeToIoTCore"
          resources:
          - "chatter"
          - "cloud_chatter"
Manifests:
  - Platform:
      os: all
    Lifecycle:
        Install: |
           docker tag <YOUR_PRIVATE_ECR_IMAGE_ID_ROS_GREENGRASS_DEMO> ros-humble-greengrass-minipupper:latest
        Startup: |
           docker-compose -f {artifacts:path}/docker-compose.yaml up -d
        Shutdown: |
           docker-compose -f {artifacts:path}/docker-compose.yaml down
    Artifacts:
      - URI: "docker:<YOUR_PRIVATE_ECR_IMAGE_ID_ROS_GREENGRASS_DEMO>"
      - URI: "s3://<YOUR_BUCKET_NAME>/com.example.ros.pupper.dance/1.0.0/artifacts/docker-compose.yaml"
